import Link from "next/link";
import AppShell from "@/components/layout/AppShell";
import { dbSelect } from "@/lib/supabase-rest";
import { createEmployeePaymentItem, liquidateEmployeePaymentItem, liquidatePayrollEmployee } from "../../domain-actions";
import { Empty, Field, input, Metric, PageTitle, primary, Section } from "../../domain-ui";
type Employee={id:string;full_name:string;employee_code:string;contract_type:string;base_salary:number};
type Item={id:string;employee_id:string;code:string;name:string;base_amount:number;rate:number;calculation_type:string;fixed_amount:number;payment_method:string;beneficiary:string|null;employees:{full_name:string}|null};
type Payment={id:string;payment_type:string;amount:number;status:string;period_start:string|null;period_end:string|null;payment_method:string;reference:string|null;employees:{full_name:string}|null};
const money=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
export default async function PayrollPage(){
 const [employees,items,payments]=await Promise.all([
  dbSelect<Employee>("employees",{select:"id,full_name,employee_code,contract_type,base_salary",status:"eq.ACTIVE",order:"full_name.asc"}),
  dbSelect<Item>("employee_payment_items",{select:"id,employee_id,code,name,base_amount,rate,calculation_type,fixed_amount,payment_method,beneficiary,employees(full_name)",is_enabled:"eq.true",order:"created_at.desc"}),
  dbSelect<Payment>("employee_payments",{select:"id,payment_type,amount,status,period_start,period_end,payment_method,reference,employees(full_name)",order:"created_at.desc",limit:50})
 ]);
 const payroll=employees.filter(x=>x.contract_type==="PAYROLL"),others=employees.filter(x=>x.contract_type!=="PAYROLL");
 return <AppShell><div className="flex justify-between gap-4"><PageTitle domain="RR. HH." title="Centro de liquidaciones" description="Nómina integral y pagos configurables por concepto."/><Link href="/hr" className="font-semibold text-orange-500">Volver a RR. HH.</Link></div>
  <div className="mt-7 grid gap-4 md:grid-cols-3"><Metric label="Empleados de nómina" value={String(payroll.length)}/><Metric label="Otros contratos" value={String(others.length)}/><Metric label="Liquidaciones" value={String(payments.length)}/></div>
  <div className="mt-7 grid gap-6 xl:grid-cols-2"><Section title="Liquidar nómina"><form action={liquidatePayrollEmployee} className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Empleado"><select required name="employee_id" className={input}><option value="">Seleccionar</option>{payroll.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></Field><Field label="Salario base"><input required type="number" min="0" name="base_salary" className={input}/></Field><Field label="Periodo inicial"><input required type="date" name="period_start" className={input}/></Field><Field label="Periodo final"><input required type="date" name="period_end" className={input}/></Field><Field label="Forma de pago"><select name="payment_method" className={input}><option value="BANK_TRANSFER">Transferencia</option><option value="CASH">Efectivo</option><option value="CHECK">Cheque</option></select></Field><Field label="Estado"><select name="status" className={input}><option value="PENDING">Pendiente</option><option value="PAID">Pagado</option></select></Field><button className={`${primary} md:col-span-2`}>Liquidar nómina</button></form></Section>
  <Section title="Configurar concepto independiente"><form action={createEmployeePaymentItem} className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Empleado"><select required name="employee_id" className={input}><option value="">Seleccionar</option>{others.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></Field><Field label="Concepto"><select name="code" className={input}><option value="ARL">ARL</option><option value="PENSION">Pensión</option><option value="HEALTH">Salud</option><option value="OTHER">Otro</option></select></Field><Field label="Nombre"><input required name="name" className={input} placeholder="ARL, pensión, salud..."/></Field><Field label="Base de liquidación"><input required type="number" min="0" name="base_amount" className={input}/></Field><Field label="Cálculo"><select name="calculation_type" className={input}><option value="PERCENTAGE">Porcentaje</option><option value="FIXED">Valor fijo</option></select></Field><Field label="Tarifa %"><input type="number" min="0" step="any" name="rate" className={input}/></Field><Field label="Valor fijo"><input type="number" min="0" name="fixed_amount" className={input}/></Field><Field label="Forma de pago"><select name="payment_method" className={input}><option value="BANK_TRANSFER">Transferencia</option><option value="CASH">Efectivo</option><option value="PSE">PSE</option><option value="PAYROLL_OPERATOR">Operador</option></select></Field><Field label="Beneficiario"><input name="beneficiary" className={input}/></Field><button className={`${primary} md:col-span-2`}>Agregar concepto</button></form></Section></div>
  <Section title="Conceptos disponibles para liquidar"><div className="mt-4 space-y-3">{items.map(item=><form action={liquidateEmployeePaymentItem} key={item.id} className="grid items-end gap-3 rounded-xl border p-4 md:grid-cols-[1fr_150px_150px_150px_auto]"><input type="hidden" name="payment_item_id" value={item.id}/><div><strong>{item.employees?.full_name} · {item.name}</strong><p className="text-sm text-zinc-500">Base {money.format(Number(item.base_amount))} · {item.calculation_type==="FIXED"?money.format(Number(item.fixed_amount)):`${item.rate}%`} · {item.payment_method}</p></div><Field label="Desde"><input type="date" name="period_start" className={input}/></Field><Field label="Hasta"><input type="date" name="period_end" className={input}/></Field><Field label="Estado"><select name="status" className={input}><option value="PENDING">Pendiente</option><option value="PAID">Pagado</option></select></Field><button className={primary}>Liquidar este ítem</button></form>)}{!items.length&&<Empty text="No hay conceptos configurados."/ >}</div></Section>
  <Section title="Historial de liquidaciones"><div className="mt-3 divide-y">{payments.map(p=><div key={p.id} className="flex justify-between py-3"><div><strong>{p.employees?.full_name} · {p.payment_type}</strong><p className="text-sm text-zinc-500">{p.period_start||"Sin periodo"} → {p.period_end||"Sin periodo"} · {p.payment_method} · {p.status}</p></div><strong>{money.format(Number(p.amount))}</strong></div>)}{!payments.length&&<Empty text="No hay liquidaciones."/ >}</div></Section>
 </AppShell>;
}
