export const defaultSecopProfile = {
  keywords: [
    "CCTV", "videovigilancia", "cámaras de seguridad", "seguridad electrónica",
    "control de acceso", "detección de incendio", "alarma contra incendio",
    "fibra óptica", "GPON", "cableado estructurado", "telecomunicaciones",
    "redes de datos", "red eléctrica", "instalaciones eléctricas",
    "audio evacuación", "pantalla LED", "sistema audiovisual",
  ],
  excluded_keywords: ["vigilancia humana", "servicio de vigilancia privada", "armamento"],
  required_keywords: [],
  sectors: ["Seguridad electrónica", "Telecomunicaciones", "Eléctrico", "Protección contra incendios", "Audiovisual"],
  unspsc_codes: ["4322", "4617", "4619", "7215", "8110"],
  departments: [],
  municipalities: [],
  modalities: [],
  preferred_entities: [],
  excluded_entities: [],
  min_value: 0,
  max_value: 0,
  minimum_days: 3,
};
