import AppShell from "@/components/layout/AppShell";
import { dbSelect } from "@/lib/supabase-rest";
import { createFinanceTransaction, createInvoice, updateInvoice } from "../domain-actions";
import { Empty, Field, input, Metric, PageTitle, primary, Section } from "../domain-ui";
type Invoice={id:string;invoice_number:string;invoice_type:string;status:string;issue_date:string;due_date:string|null;total:number;paid_amount:number;clients:{name:string}|null;projects:{name:string}|null};
type Transaction={id:string;transaction_type:string;category:string|null;description:string;amount:number;transaction_date:string;projects:{name:string}|null};
const money=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
export default async function FinancePage(){
 const [companies,clients,projects,invoices,transactions]=await Promise.all([
  dbSelect<{id:string;name:string}>("companies",{select:"id,name"}),dbSelect<{id:string;name:string}>("clients",{select:"id,name",order:"name.asc"}),dbSelect<{id:string;name:string}>("projects",{select:"id,name",order:"name.asc"}),
  dbSelect<Invoice>("invoices",{select:"id,invoice_number,invoice_type,status,issue_date,due_date,total,paid_amount,clients(name),projects(name)",order:"issue_date.desc"}),
  dbSelect<Transaction>("finance_transactions",{select:"id,transaction_type,category,description,amount,transaction_date,projects(name)",order:"transaction_date.desc"})
 ]);
 const income=transactions.filter(x=>x.transaction_type==="INCOME").reduce((s,x)=>s+Number(x.amount),0);
 const expense=transactions.filter(x=>x.transaction_type==="EXPENSE").reduce((s,x)=>s+Number(x.amount),0);
 const receivable=invoices.reduce((s,x)=>s+Math.max(0,Number(x.total)-Number(x.paid_amount)),0);
 return <AppShell><PageTitle domain="Control financiero" title="Finanzas" description="Facturación, cartera, ingresos y egresos operativos."/>
  <div className="mt-7 grid gap-4 md:grid-cols-4"><Metric label="Ingresos" value={money.format(income)}/><Metric label="Egresos" value={money.format(expense)}/><Metric label="Balance" value={money.format(income-expense)}/><Metric label="Cartera" value={money.format(receivable)}/></div>
  <div className="mt-7 grid gap-6 xl:grid-cols-2"><Section title="Nueva factura"><form action={createInvoice} className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Empresa"><select required name="company_id" className={input}><option value="">Seleccionar</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Número"><input required name="invoice_number" className={input}/></Field><Field label="Cliente"><select name="client_id" className={input}><option value="">Sin cliente</option>{clients.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Proyecto"><select name="project_id" className={input}><option value="">Sin proyecto</option>{projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Tipo"><select name="invoice_type" className={input}><option value="SALE">Venta</option><option value="PURCHASE">Compra</option></select></Field><Field label="Estado"><select name="status" className={input}><option value="DRAFT">Borrador</option><option value="ISSUED">Emitida</option></select></Field><Field label="Emisión"><input type="date" name="issue_date" className={input}/></Field><Field label="Vencimiento"><input type="date" name="due_date" className={input}/></Field><Field label="Total"><input required type="number" min="0" step="any" name="total" className={input}/></Field><div className="flex items-end"><button className={`${primary} w-full`}>Crear factura</button></div></form></Section>
   <Section title="Nuevo movimiento"><form action={createFinanceTransaction} className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Empresa"><select required name="company_id" className={input}><option value="">Seleccionar</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Tipo"><select name="transaction_type" className={input}><option value="INCOME">Ingreso</option><option value="EXPENSE">Egreso</option></select></Field><Field label="Categoría"><input name="category" className={input}/></Field><Field label="Proyecto"><select name="project_id" className={input}><option value="">Sin proyecto</option>{projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Descripción"><input required name="description" className={input}/></Field><Field label="Valor"><input required type="number" min="0" step="any" name="amount" className={input}/></Field><Field label="Fecha"><input type="date" name="transaction_date" className={input}/></Field><div className="flex items-end"><button className={`${primary} w-full`}>Registrar movimiento</button></div></form></Section></div>
  <div className="mt-7 grid gap-6 xl:grid-cols-2"><Section title="Facturas"><div className="mt-3 divide-y">{invoices.map(x=><div key={x.id} className="py-3"><div className="flex justify-between"><strong>{x.invoice_number} · {x.clients?.name||"Sin cliente"}</strong><span>{money.format(Number(x.total))}</span></div><p className="text-xs text-zinc-500">{x.projects?.name||"Sin proyecto"} · {x.issue_date} · saldo {money.format(Number(x.total)-Number(x.paid_amount))}</p><form action={updateInvoice} className="mt-2 flex gap-2"><input type="hidden" name="invoice_id" value={x.id}/><select name="status" defaultValue={x.status} className="rounded-lg border px-2"><option value="DRAFT">Borrador</option><option value="ISSUED">Emitida</option><option value="PARTIAL">Pago parcial</option><option value="PAID">Pagada</option><option value="VOID">Anulada</option></select><input type="number" min="0" step="any" name="paid_amount" defaultValue={x.paid_amount} className="w-32 rounded-lg border px-2"/><button className="rounded-lg bg-zinc-950 px-3 text-white">Guardar</button></form></div>)}{!invoices.length&&<Empty text="No hay facturas."/ >}</div></Section>
   <Section title="Movimientos"><div className="mt-3 divide-y">{transactions.map(x=><div key={x.id} className="flex justify-between py-3"><div><p className="font-semibold">{x.description}</p><p className="text-xs text-zinc-500">{x.category||"Sin categoría"} · {x.projects?.name||"Sin proyecto"} · {x.transaction_date}</p></div><strong className={x.transaction_type==="INCOME"?"text-green-600":"text-red-600"}>{x.transaction_type==="INCOME"?"+":"−"}{money.format(Number(x.amount))}</strong></div>)}{!transactions.length&&<Empty text="No hay movimientos."/ >}</div></Section></div>
 </AppShell>;
}
