import AppShell from "@/components/layout/AppShell";
import { dbSelect } from "@/lib/supabase-rest";
import { createPurchaseOrder, createPurchaseOrderItem, createSupplier, receivePurchaseOrderItem, updatePurchaseOrder } from "../domain-actions";
import { Empty, Field, input, Metric, PageTitle, primary, Section } from "../domain-ui";
type Supplier={id:string;name:string;nit:string|null;status:string};
type Order={id:string;order_number:string;status:string;issue_date:string;expected_date:string|null;total:number;suppliers:{name:string}|null;projects:{name:string}|null};
type Item={id:string;purchase_order_id:string;product_id:string|null;delivery_destination:string;description:string;quantity:number;received_quantity:number;unit_cost:number};
type CatalogProduct={id:string;internal_sku:string|null;name:string;supplier_prices:{unit_price:number;suppliers:{name:string}|null}[]};
const money=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
export default async function PurchasingPage(){
 const [companies,projects,suppliers,orders,items,catalogProducts]=await Promise.all([
  dbSelect<{id:string;name:string}>("companies",{select:"id,name"}),dbSelect<{id:string;name:string}>("projects",{select:"id,name",order:"name.asc"}),
  dbSelect<Supplier>("suppliers",{select:"id,name,nit,status",order:"created_at.desc"}),dbSelect<Order>("purchase_orders",{select:"id,order_number,status,issue_date,expected_date,total,suppliers(name),projects(name)",order:"created_at.desc"}),
  dbSelect<Item>("purchase_order_items",{select:"id,purchase_order_id,product_id,delivery_destination,description,quantity,received_quantity,unit_cost",order:"created_at.desc"}),
  dbSelect<CatalogProduct>("catalog_products",{select:"id,internal_sku,name,supplier_prices(unit_price,suppliers(name))",active:"eq.true",order:"name.asc"})
 ]);
 return <AppShell><PageTitle domain="Abastecimiento" title="Compras" description="Proveedores, órdenes de compra y partidas."/>
  <div className="mt-7 grid gap-4 md:grid-cols-3"><Metric label="Proveedores" value={String(suppliers.length)}/><Metric label="Órdenes abiertas" value={String(orders.filter(x=>!["RECEIVED","CANCELLED"].includes(x.status)).length)}/><Metric label="Total ordenado" value={money.format(orders.reduce((s,x)=>s+Number(x.total||0),0))}/></div>
  <div className="mt-7 grid gap-6 xl:grid-cols-3"><Section title="Nuevo proveedor"><form action={createSupplier} className="mt-5 space-y-4"><Field label="Empresa"><select required name="company_id" className={input}><option value="">Seleccionar</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Nombre"><input required name="name" className={input}/></Field><Field label="NIT"><input name="nit" className={input}/></Field><Field label="Correo"><input type="email" name="email" className={input}/></Field><Field label="Teléfono"><input name="phone" className={input}/></Field><button className={`${primary} w-full`}>Crear proveedor</button></form></Section>
  <div className="xl:col-span-2"><Section title="Nueva orden de compra"><form action={createPurchaseOrder} className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Empresa"><select required name="company_id" className={input}><option value="">Seleccionar</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Número"><input required name="order_number" className={input}/></Field><Field label="Proveedor"><select name="supplier_id" className={input}><option value="">Seleccionar</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Proyecto"><select name="project_id" className={input}><option value="">Sin proyecto</option>{projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Fecha"><input type="date" name="issue_date" className={input}/></Field><Field label="Entrega esperada"><input type="date" name="expected_date" className={input}/></Field><button className={`${primary} md:col-span-2`}>Crear orden</button></form></Section></div></div>
  <div className="mt-7 space-y-4">{orders.map(o=><section key={o.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="font-bold">{o.order_number} · {o.suppliers?.name||"Sin proveedor"}</h2><p className="text-sm text-zinc-500">{o.projects?.name||"Sin proyecto"} · {o.issue_date} · {money.format(Number(o.total||0))}</p></div><form action={updatePurchaseOrder} className="flex gap-2"><input type="hidden" name="purchase_order_id" value={o.id}/><select name="status" defaultValue={o.status} className="rounded-xl border px-3"><option value="DRAFT">Borrador</option><option value="APPROVED">Aprobada</option><option value="ORDERED">Ordenada</option><option value="PARTIAL">Parcial</option><option value="RECEIVED">Recibida</option><option value="CANCELLED">Cancelada</option></select><button className="rounded-xl bg-zinc-950 px-4 text-white">Guardar</button></form></div>
   <form action={createPurchaseOrderItem} className="mt-4 grid gap-3 rounded-xl bg-zinc-50 p-4 md:grid-cols-6"><input type="hidden" name="purchase_order_id" value={o.id}/><select required name="product_id" className={`${input} md:col-span-2`}><option value="">Buscar en catálogo</option>{catalogProducts.map(item=><option key={item.id} value={item.id}>{item.internal_sku||"S/C"} · {item.name}</option>)}</select><input name="description" placeholder="Descripción (opcional)" className={input}/><input required type="number" min="0.01" step="any" name="quantity" defaultValue="1" className={input}/><input required type="number" min="0" step="any" name="unit_cost" placeholder="Costo unitario" className={input}/><select name="delivery_destination" className={input}><option value="PROJECT">Entrega directa al proyecto</option><option value="WAREHOUSE">Ingreso a bodega</option></select><button className="rounded-xl bg-orange-500 px-4 py-3 font-semibold text-white md:col-span-6">Agregar partida</button></form>
   <div className="mt-3 divide-y">{items.filter(i=>i.purchase_order_id===o.id).map(i=>{const pending=Number(i.quantity)-Number(i.received_quantity);return <div key={i.id} className="flex flex-wrap items-center justify-between gap-3 py-3 text-sm"><div><span className="font-semibold">{i.description} · {i.quantity}</span><p className="text-xs text-zinc-500">{i.delivery_destination==="PROJECT"?"Directo al proyecto":"Bodega residual"} · Recibido {i.received_quantity} · Pendiente {pending}</p></div><strong>{money.format(Number(i.quantity)*Number(i.unit_cost))}</strong>{pending>0&&i.product_id&&<form action={receivePurchaseOrderItem} className="flex gap-2"><input type="hidden" name="purchase_order_id" value={o.id}/><input type="hidden" name="purchase_order_item_id" value={i.id}/><input aria-label="Cantidad recibida" required type="number" name="receive_quantity" min="0.01" max={pending} step="any" defaultValue={pending} className="w-28 rounded-xl border px-3"/><button className="rounded-xl bg-green-600 px-4 py-2 font-semibold text-white">Recibir</button></form>}</div>})}</div>
  </section>)}{!orders.length&&<Empty text="No hay órdenes de compra."/>}</div>
 </AppShell>;
}
