import AppShell from "@/components/layout/AppShell";
import { dbSelect } from "@/lib/supabase-rest";
import { createSstIncident, createSstInspection, updateSstIncident } from "../domain-actions";
import { Empty, Field, input, Metric, PageTitle, primary, Section } from "../domain-ui";
type Incident={id:string;incident_date:string;incident_type:string;severity:string;status:string;description:string;corrective_action:string|null;employees:{full_name:string}|null;projects:{name:string}|null};
type Inspection={id:string;inspection_date:string;inspection_type:string;result:string;inspector:string|null;findings:string|null;projects:{name:string}|null};
export default async function SstPage(){
 const [companies,employees,projects,incidents,inspections]=await Promise.all([
  dbSelect<{id:string;name:string}>("companies",{select:"id,name"}),dbSelect<{id:string;full_name:string}>("employees",{select:"id,full_name",status:"eq.ACTIVE",order:"full_name.asc"}),dbSelect<{id:string;name:string}>("projects",{select:"id,name",order:"name.asc"}),
  dbSelect<Incident>("sst_incidents",{select:"id,incident_date,incident_type,severity,status,description,corrective_action,employees(full_name),projects(name)",order:"incident_date.desc"}),
  dbSelect<Inspection>("sst_inspections",{select:"id,inspection_date,inspection_type,result,inspector,findings,projects(name)",order:"inspection_date.desc"})
 ]);
 return <AppShell><PageTitle domain="Seguridad y salud" title="SST" description="Incidentes, acciones correctivas e inspecciones."/>
  <div className="mt-7 grid gap-4 md:grid-cols-3"><Metric label="Incidentes abiertos" value={String(incidents.filter(x=>x.status!=="CLOSED").length)}/><Metric label="Severidad alta" value={String(incidents.filter(x=>["HIGH","CRITICAL"].includes(x.severity)&&x.status!=="CLOSED").length)}/><Metric label="Inspecciones" value={String(inspections.length)}/></div>
  <div className="mt-7 grid gap-6 xl:grid-cols-2"><Section title="Registrar incidente"><form action={createSstIncident} className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Empresa"><select required name="company_id" className={input}><option value="">Seleccionar</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Fecha"><input required type="date" name="incident_date" className={input}/></Field><Field label="Empleado"><select name="employee_id" className={input}><option value="">Sin empleado</option>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></Field><Field label="Proyecto"><select name="project_id" className={input}><option value="">Sin proyecto</option>{projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Tipo"><input required name="incident_type" className={input}/></Field><Field label="Severidad"><select name="severity" className={input}><option value="LOW">Baja</option><option value="MEDIUM">Media</option><option value="HIGH">Alta</option><option value="CRITICAL">Crítica</option></select></Field><div className="md:col-span-2"><Field label="Descripción"><textarea required name="description" className={input}/></Field></div><button className={`${primary} md:col-span-2`}>Registrar incidente</button></form></Section>
   <Section title="Registrar inspección"><form action={createSstInspection} className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Empresa"><select required name="company_id" className={input}><option value="">Seleccionar</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Fecha"><input required type="date" name="inspection_date" className={input}/></Field><Field label="Proyecto"><select name="project_id" className={input}><option value="">Sin proyecto</option>{projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Tipo"><input required name="inspection_type" className={input}/></Field><Field label="Inspector"><input name="inspector" className={input}/></Field><Field label="Resultado"><select name="result" className={input}><option value="PENDING">Pendiente</option><option value="COMPLIANT">Conforme</option><option value="WITH_FINDINGS">Con hallazgos</option></select></Field><div className="md:col-span-2"><Field label="Hallazgos"><textarea name="findings" className={input}/></Field></div><button className={`${primary} md:col-span-2`}>Registrar inspección</button></form></Section></div>
  <div className="mt-7 grid gap-6 xl:grid-cols-2"><Section title="Incidentes"><div className="mt-3 divide-y">{incidents.map(x=><div key={x.id} className="py-3"><p className="font-semibold">{x.incident_type} · {x.severity}</p><p className="text-sm text-zinc-500">{x.incident_date} · {x.employees?.full_name||"Sin empleado"} · {x.projects?.name||"Sin proyecto"}</p><p className="mt-1 text-sm">{x.description}</p><form action={updateSstIncident} className="mt-2 grid gap-2 md:grid-cols-[130px_1fr_auto]"><input type="hidden" name="incident_id" value={x.id}/><select name="status" defaultValue={x.status} className="rounded-lg border px-2"><option value="OPEN">Abierto</option><option value="INVESTIGATING">Investigación</option><option value="CLOSED">Cerrado</option></select><input name="corrective_action" defaultValue={x.corrective_action||""} placeholder="Acción correctiva" className="rounded-lg border px-2"/><button className="rounded-lg bg-zinc-950 px-3 text-white">Guardar</button></form></div>)}{!incidents.length&&<Empty text="No hay incidentes."/ >}</div></Section>
   <Section title="Inspecciones"><div className="mt-3 divide-y">{inspections.map(x=><div key={x.id} className="py-3"><div className="flex justify-between"><strong>{x.inspection_type}</strong><span className="text-xs font-bold">{x.result}</span></div><p className="text-sm text-zinc-500">{x.inspection_date} · {x.projects?.name||"Sin proyecto"} · {x.inspector||"Sin inspector"}</p>{x.findings&&<p className="mt-1 text-sm">{x.findings}</p>}</div>)}{!inspections.length&&<Empty text="No hay inspecciones."/ >}</div></Section></div>
 </AppShell>;
}
