import AppShell from "@/components/layout/AppShell";
import { dbSelect } from "@/lib/supabase-rest";
import { createInventoryItem, createInventoryMovement } from "../domain-actions";
import { Empty, Field, input, Metric, PageTitle, primary, Section } from "../domain-ui";
type Item={id:string;sku:string;name:string;category:string|null;unit:string;current_stock:number;min_stock:number;unit_cost:number};
type Movement={id:string;item_id:string;movement_type:string;quantity:number;reference:string|null;movement_date:string;inventory_items:{name:string}|null;projects:{name:string}|null};
const money=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
export default async function InventoryPage(){
 const [companies,projects,items,movements]=await Promise.all([
  dbSelect<{id:string;name:string}>("companies",{select:"id,name"}),dbSelect<{id:string;name:string}>("projects",{select:"id,name",order:"name.asc"}),
  dbSelect<Item>("inventory_items",{select:"id,sku,name,category,unit,current_stock,min_stock,unit_cost",order:"name.asc"}),
  dbSelect<Movement>("inventory_movements",{select:"id,item_id,movement_type,quantity,reference,movement_date,inventory_items(name),projects(name)",order:"movement_date.desc",limit:25})
 ]);
 const value=items.reduce((s,x)=>s+Number(x.current_stock)*Number(x.unit_cost),0);
 return <AppShell><PageTitle domain="Operaciones" title="Inventario" description="Catálogo, existencias, entradas y salidas por proyecto."/>
  <div className="mt-7 grid gap-4 md:grid-cols-3"><Metric label="Artículos" value={String(items.length)}/><Metric label="Bajo mínimo" value={String(items.filter(x=>Number(x.current_stock)<=Number(x.min_stock)).length)}/><Metric label="Valor inventario" value={money.format(value)}/></div>
  <div className="mt-7 grid gap-6 xl:grid-cols-2"><Section title="Nuevo artículo"><form action={createInventoryItem} className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Empresa"><select required name="company_id" className={input}><option value="">Seleccionar</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="SKU"><input required name="sku" className={input}/></Field><Field label="Nombre"><input required name="name" className={input}/></Field><Field label="Categoría"><input name="category" className={input}/></Field><Field label="Unidad"><input name="unit" defaultValue="UND" className={input}/></Field><Field label="Existencia inicial"><input type="number" step="any" name="current_stock" className={input}/></Field><Field label="Stock mínimo"><input type="number" step="any" name="min_stock" className={input}/></Field><Field label="Costo unitario"><input type="number" min="0" step="any" name="unit_cost" className={input}/></Field><button className={`${primary} md:col-span-2`}>Crear artículo</button></form></Section>
   <Section title="Movimiento"><form action={createInventoryMovement} className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Artículo"><select required name="item_id" className={input}><option value="">Seleccionar</option>{items.map(x=><option key={x.id} value={x.id}>{x.sku} · {x.name} ({x.current_stock})</option>)}</select></Field><Field label="Tipo"><select name="movement_type" className={input}><option value="IN">Entrada</option><option value="OUT">Salida</option><option value="ADJUSTMENT">Ajuste positivo</option></select></Field><Field label="Cantidad"><input required type="number" min="0.01" step="any" name="quantity" className={input}/></Field><Field label="Proyecto"><select name="project_id" className={input}><option value="">Sin proyecto</option>{projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Referencia"><input name="reference" className={input}/></Field><Field label="Notas"><input name="notes" className={input}/></Field><button className={`${primary} md:col-span-2`}>Registrar movimiento</button></form></Section></div>
  <div className="mt-7 overflow-hidden rounded-2xl border bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-zinc-50"><tr><th className="p-4">Artículo</th><th>SKU</th><th>Existencia</th><th>Mínimo</th><th>Valor</th></tr></thead><tbody className="divide-y">{items.map(x=><tr key={x.id}><td className="p-4 font-semibold">{x.name}</td><td>{x.sku}</td><td className={Number(x.current_stock)<=Number(x.min_stock)?"font-bold text-red-600":""}>{x.current_stock} {x.unit}</td><td>{x.min_stock}</td><td>{money.format(Number(x.current_stock)*Number(x.unit_cost))}</td></tr>)}</tbody></table>{!items.length&&<Empty text="No hay artículos en inventario."/>}</div>
  <Section title="Últimos movimientos"><div className="mt-3 divide-y">{movements.map(m=><div key={m.id} className="flex justify-between py-3"><div><p className="font-semibold">{m.inventory_items?.name}</p><p className="text-xs text-zinc-500">{m.projects?.name||m.reference||"Sin referencia"} · {new Date(m.movement_date).toLocaleString("es-CO")}</p></div><strong className={m.movement_type==="OUT"?"text-red-600":"text-green-600"}>{m.movement_type==="OUT"?"−":"+"}{m.quantity}</strong></div>)}{!movements.length&&<Empty text="No hay movimientos."/>}</div></Section>
 </AppShell>;
}
