import Link from "next/link";
import { notFound } from "next/navigation";
import AppShell from "@/components/layout/AppShell";
import { dbSelect } from "@/lib/supabase-rest";
import { createDocument, createMilestone, createTask, updateProjectStatus, updateTask } from "../actions";
import { createProjectMaterialRequirement } from "@/app/domain-actions";

type Project={id:string;project_code:string;name:string;description:string|null;project_type:string;status:string;progress:number;contract_value:number;budget_cost:number;clients:{name:string}|null};
type Task={id:string;title:string;status:string;priority:string;progress:number;due_date:string|null;profiles:{full_name:string|null}|null};
type Milestone={id:string;name:string;status:string;due_date:string|null};
type Document={id:string;document_code:string;title:string;document_type:string;revision:string;status:string;discipline:string|null};
type Profile={id:string;full_name:string|null};
type CatalogProduct={id:string;internal_sku:string|null;name:string;unit:string};
type MaterialRequirement={id:string;quantity_required:number;quantity_purchased:number;quantity_delivered:number;quantity_installed:number;quantity_returned:number;catalog_products:{name:string;unit:string}|null};
const input="mt-2 w-full rounded-xl border border-zinc-300 px-3 py-2.5 outline-none focus:border-orange-500";
const money=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});

export default async function ProjectDetailPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;
 const [project]=await dbSelect<Project>("projects",{select:"id,project_code,name,description,project_type,status,progress,contract_value,budget_cost,clients(name)",id:`eq.${id}`});
 if(!project)notFound();
 const [tasks,milestones,documents,profiles,products,requirements]=await Promise.all([
  dbSelect<Task>("project_tasks",{select:"id,title,status,priority,progress,due_date,profiles!project_tasks_assigned_to_fkey(full_name)",project_id:`eq.${id}`,order:"created_at.desc"}),
  dbSelect<Milestone>("project_milestones",{select:"id,name,status,due_date",project_id:`eq.${id}`,order:"sort_order.asc,created_at.asc"}),
  dbSelect<Document>("engineering_documents",{select:"id,document_code,title,document_type,revision,status,discipline",project_id:`eq.${id}`,order:"created_at.desc"}),
  dbSelect<Profile>("profiles",{select:"id,full_name",is_active:"eq.true",order:"full_name.asc"}),
  dbSelect<CatalogProduct>("catalog_products",{select:"id,internal_sku,name,unit",active:"eq.true",order:"name.asc"}),
  dbSelect<MaterialRequirement>("project_material_requirements",{select:"id,quantity_required,quantity_purchased,quantity_delivered,quantity_installed,quantity_returned,catalog_products(name,unit)",project_id:`eq.${id}`,order:"created_at.asc"})
 ]);
 return <AppShell>
  <div className="flex flex-wrap items-start justify-between gap-5"><div><Link href="/projects" className="text-sm font-semibold text-orange-600">← Portafolio</Link><p className="mt-4 text-sm font-semibold uppercase tracking-widest text-zinc-500">{project.project_code} · {project.project_type}</p><h1 className="mt-1 text-3xl font-bold">{project.name}</h1><p className="mt-2 max-w-3xl text-zinc-500">{project.description||"Sin descripción"}</p></div><form action={updateProjectStatus} className="flex items-end gap-3 rounded-2xl border bg-white p-4 shadow-sm"><input type="hidden" name="project_id" value={id}/><label className="text-xs font-semibold text-zinc-500">Estado<select name="status" defaultValue={project.status} className={input}><option value="PLANNING">Planeación</option><option value="ACTIVE">Activo</option><option value="ON_HOLD">Suspendido</option><option value="COMPLETED">Completado</option><option value="CANCELLED">Cancelado</option></select></label><label className="text-xs font-semibold text-zinc-500">Avance<input name="progress" type="number" min="0" max="100" defaultValue={project.progress} className={`${input} w-24`}/></label><button className="rounded-xl bg-zinc-950 px-4 py-3 font-semibold text-white">Actualizar</button></form></div>
  <div className="mt-7 grid gap-4 md:grid-cols-4"><Metric label="Cliente" value={project.clients?.name||"Sin cliente"}/><Metric label="Contrato" value={money.format(Number(project.contract_value||0))}/><Metric label="Presupuesto" value={money.format(Number(project.budget_cost||0))}/><Metric label="Avance" value={`${Number(project.progress)}%`}/></div>
  <Section title="Equipos y materiales requeridos" count={requirements.length}>
    <form action={createProjectMaterialRequirement} className="grid gap-3 rounded-xl bg-zinc-50 p-4 md:grid-cols-[2fr_140px_1fr_auto]">
      <input type="hidden" name="project_id" value={id}/>
      <select required name="product_id" className={input}><option value="">Buscar producto en el catálogo</option>{products.map(product=><option key={product.id} value={product.id}>{product.internal_sku||"S/C"} · {product.name}</option>)}</select>
      <input required type="number" min="0.01" step="any" name="quantity_required" placeholder="Cantidad" className={input}/>
      <input name="notes" placeholder="Uso o ubicación" className={input}/>
      <button className="mt-2 rounded-xl bg-yellow-500 px-4 font-semibold text-black">Agregar</button>
    </form>
    <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="text-zinc-500"><tr><th className="py-3">Material</th><th>Requerido</th><th>Comprado</th><th>Entregado</th><th>Instalado</th><th>Sobrante devuelto</th></tr></thead><tbody className="divide-y">{requirements.map(item=><tr key={item.id}><td className="py-3 font-semibold">{item.catalog_products?.name}</td><td>{item.quantity_required} {item.catalog_products?.unit}</td><td>{item.quantity_purchased}</td><td>{item.quantity_delivered}</td><td>{item.quantity_installed}</td><td>{item.quantity_returned}</td></tr>)}</tbody></table>{!requirements.length&&<Empty text="Aún no hay materiales requeridos."/ >}</div>
  </Section>
  <Section title="Tareas" count={tasks.length}><form action={createTask} className="grid gap-3 rounded-xl bg-zinc-50 p-4 md:grid-cols-6"><input type="hidden" name="project_id" value={id}/><input name="title" required placeholder="Nueva tarea" className={`${input} md:col-span-2`}/><select name="assigned_to" className={input}><option value="">Responsable</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select><select name="milestone_id" className={input}><option value="">Hito</option>{milestones.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><input type="date" name="due_date" className={input}/><button className="mt-2 rounded-xl bg-orange-500 px-4 font-semibold text-white">Agregar</button></form><div className="mt-4 divide-y">{tasks.map(t=><div key={t.id} className="grid items-center gap-3 py-4 md:grid-cols-[1fr_120px_250px]"><div><p className="font-semibold">{t.title}</p><p className="text-xs text-zinc-500">{t.profiles?.full_name||"Sin responsable"} · {t.due_date||"sin fecha"}</p></div><span className="text-sm font-semibold">{Number(t.progress)}%</span><form action={updateTask} className="flex gap-2"><input type="hidden" name="project_id" value={id}/><input type="hidden" name="task_id" value={t.id}/><select name="status" defaultValue={t.status} className="rounded-lg border px-2"><option value="TODO">Pendiente</option><option value="IN_PROGRESS">En curso</option><option value="BLOCKED">Bloqueada</option><option value="DONE">Terminada</option></select><input name="progress" type="number" min="0" max="100" defaultValue={t.progress} className="w-20 rounded-lg border px-2"/><button className="rounded-lg bg-zinc-900 px-3 text-white">OK</button></form></div>)}{!tasks.length&&<Empty text="No hay tareas."/>}</div></Section>
  <div className="mt-6 grid gap-6 xl:grid-cols-2"><Section title="Hitos" count={milestones.length}><form action={createMilestone} className="grid gap-3 rounded-xl bg-zinc-50 p-4 md:grid-cols-[1fr_160px_auto]"><input type="hidden" name="project_id" value={id}/><input name="name" required placeholder="Nuevo hito" className={input}/><input type="date" name="due_date" className={input}/><button className="mt-2 rounded-xl bg-orange-500 px-4 font-semibold text-white">Agregar</button></form><div className="mt-3 divide-y">{milestones.map(m=><div key={m.id} className="flex justify-between py-3"><div><p className="font-semibold">{m.name}</p><p className="text-xs text-zinc-500">{m.due_date||"Sin fecha"}</p></div><span className="text-xs font-semibold">{m.status}</span></div>)}{!milestones.length&&<Empty text="No hay hitos."/>}</div></Section><Section title="Documentos" count={documents.length}><form action={createDocument} className="grid gap-3 rounded-xl bg-zinc-50 p-4 md:grid-cols-2"><input type="hidden" name="project_id" value={id}/><input name="document_code" required placeholder="Código" className={input}/><input name="title" required placeholder="Título" className={input}/><input name="document_type" required placeholder="Tipo" className={input}/><input name="discipline" placeholder="Disciplina" className={input}/><input name="revision" defaultValue="0" className={input}/><button className="mt-2 rounded-xl bg-orange-500 px-4 font-semibold text-white">Registrar</button></form><div className="mt-3 divide-y">{documents.map(d=><div key={d.id} className="flex justify-between py-3"><div><p className="font-semibold">{d.document_code} · {d.title}</p><p className="text-xs text-zinc-500">{d.document_type} · Rev. {d.revision}</p></div><span className="text-xs font-semibold">{d.status}</span></div>)}{!documents.length&&<Empty text="No hay documentos."/>}</div></Section></div>
 </AppShell>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-zinc-500">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></div>}
function Section({title,count,children}:{title:string;count:number;children:React.ReactNode}){return <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="mb-4 flex justify-between"><h2 className="text-xl font-bold">{title}</h2><span className="rounded-full bg-zinc-100 px-3 py-1 text-xs font-semibold">{count}</span></div>{children}</section>}
function Empty({text}:{text:string}){return <p className="py-8 text-center text-sm text-zinc-500">{text}</p>}
